name: Test and Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # Run on version tags like v1.0.0
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Run blocker tests
      working-directory: go_security_app
      run: go test -short
  
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['amd64', 'arm64']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Build for ${{ matrix.arch }}
      working-directory: go_security_app
      run: GOOS=linux GOARCH=${{ matrix.arch }} go build -o request_security_checker-linux-${{ matrix.arch }}
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: request_security_checker-linux-${{ matrix.arch }}
        path: go_security_app/request_security_checker-linux-${{ matrix.arch }}
        retention-days: 7

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: List downloaded artifacts
      run: ls -R artifacts
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          artifacts/request_security_checker-linux-amd64/request_security_checker-linux-amd64
          artifacts/request_security_checker-linux-arm64/request_security_checker-linux-arm64